version: '3.9'

services:
  app:
    build: ./app
    container_name: my-web
    expose:
      - "3000"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
      - ./docker/start.sh:/start.sh
    command: /bin/sh /start.sh

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    entrypoint: >
      /bin/sh -c "trap exit TERM; while :; do sleep 12h & wait $${!};
      certbot renew --webroot -w /var/www/certbot; done;"
