version: '3.9'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    depends_on:
      - app

  app:
    build: .
    container_name: my-web
    expose:
      - "3000"
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./docker/certbot/conf:/etc/letsencrypt
      - ./docker/certbot/www:/var/www/certbot
    environment:
      - DOMAIN=xaturno.mx
      - EMAIL=xaturnowebservices@gmail.com
    entrypoint: >
      /bin/sh -c "
        # Crear certificados si no existen
        if [ ! -f /etc/letsencrypt/live/$${DOMAIN}/fullchain.pem ]; then
          certbot certonly --webroot -w /var/www/certbot \
            -d $${DOMAIN} -d www.$${DOMAIN} \
            --email $${EMAIL} --agree-tos --no-eff-email;
        fi;
        # Loop de renovación
        trap exit TERM;
        while :; do
          sleep 12h & wait $${!};
          certbot renew --webroot -w /var/www/certbot;
        done;
      "
